#############################################################################
# Makefile for building: libHack01.so
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  Hack01.pro
# Template: app
# Command: C:\Qt\Qt5.9.1\5.9.1\android_armv7\bin\qmake.exe -o Makefile Hack01.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc
CXX           = C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_ANDROIDEXTRAS_LIB -DQT_CORE_LIB
CFLAGS        = -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/platforms/android-16/arch-arm/ -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/platforms/android-16/arch-arm/ -g -g -marm -O0 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQuick -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtNetwork -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtAndroidExtras -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore -I. -I..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include -I..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include -I..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include -I..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\android-g++
QMAKE         = C:\Qt\Qt5.9.1\5.9.1\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.9.1\5.9.1\android_armv7\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.9.1\5.9.1\android_armv7\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = libHack01.so1.0.0
DISTDIR = C:\Users\A6654\Desktop\hack01_1\.tmp\libHack01.so1.0.0
LINK          = C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/platforms/android-16/arch-arm/ -Wl,-soname,libHack01.so -Wl,-rpath=C:/Qt/Qt5.9.1/5.9.1/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -LC:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/platforms/android-16/arch-arm//usr/lib -Lc:/users/a6654/appdata/local/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x -LC:/Qt/Qt5.9.1/5.9.1/android_armv7/lib -lQt5Quick -Lc:\utils\android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Lc:\utils\android-ndk-r10e/platforms/android-16/arch-arm//usr/lib -Lc:/utils/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/../lib/gcc/arm-linux-androideabi/4.9 -LC:\Qt\Qt5.9.1\5.9.1\android_armv7/lib -lQt5Qml -lQt5Network -lQt5Gui -lQt5AndroidExtras -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          =   main.cpp
QMAKE_TARGET  = libHack01.so
DESTDIR       = 
TARGET        = libHack01.so


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Hack01.pro ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\android-g++\qmake.conf ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\spec_pre.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\unix.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\linux.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\sanitize.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\gcc-base.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\gcc-base-unix.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\qdevice.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\device_config.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\android-base-head.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\qconfig.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_location.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\android-base-tail.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\android-g++\qmake.conf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\spec_post.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\toolchain.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\resolve_config.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qml_debug.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\android\android.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\resources.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\moc.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\unix\opengl.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\unix\thread.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qmake_use.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\file_copies.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\exceptions.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\lex.prf \
		Hack01.pro \
		qml.qrc \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Quick.prl \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Qml.prl \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Network.prl \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Gui.prl \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5AndroidExtras.prl \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Core.prl
	$(QMAKE) -o Makefile Hack01.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\spec_pre.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\unix.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\linux.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\sanitize.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\gcc-base.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\gcc-base-unix.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\qdevice.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\device_config.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\android-base-head.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\qconfig.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_charts.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_location.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webview.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\common\android-base-tail.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\android-g++\qmake.conf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\spec_post.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\toolchain.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\resolve_config.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\default_post.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qml_debug.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\android\android.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qt.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\resources.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\moc.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\unix\opengl.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\unix\thread.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\qmake_use.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\file_copies.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\testcase_targets.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\exceptions.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\yacc.prf:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\lex.prf:
Hack01.pro:
qml.qrc:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Quick.prl:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Qml.prl:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Network.prl:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Gui.prl:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5AndroidExtras.prl:
..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Hack01.pro -spec android-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\bin\rcc.exe \
		MainPageForm.ui.qml \
		MainPage.qml \
		SettingPageForm.ui.qml \
		SettingPage.qml \
		qtquickcontrols2.conf \
		main.qml \
		images\IMG_00000005.jpg
	C:\Qt\Qt5.9.1\5.9.1\android_armv7\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\data\dummy.cpp
	C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=C:\Users\A6654\AppData\Local\Android\sdk\ndk-bundle/platforms/android-16/arch-arm/ -g -g -marm -O0 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.obj: main.cpp ..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QGuiApplication \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qguiapplication.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtguiglobal.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qglobal.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\type_traits \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\c++0x_warning.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++config.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\os_defines.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\cpu_defines.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdint \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdint.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\_wchar_limits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\android\api-level.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstddef \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\utility \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_relops.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_pair.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\move.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\concept_check.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\boost_concept_check.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\initializer_list \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qconfig-bootstrapped.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qconfig.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtcore-config.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsystemdetection.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qprocessordetection.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcompilerdetection.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\algorithm \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algobase.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functexcept.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_defines.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cpp_type_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\type_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\numeric_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_funcs.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\debug.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\macros.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\functions.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_function.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\backward\binders.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\formatter.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\typeinfo \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\exception \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_lockfree_defines.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_ptr.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\nested_exception.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hash_bytes.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ptr_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\predefined_ops.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algobase.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\features.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\basic_iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\parallel.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compiletime_settings.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdio \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdio.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\cdefs.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\cdefs_elf.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\posix_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\stddef.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\compiler.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\posix_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\kernel.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\sysmacros.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdlib \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\stdlib.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\string.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\malloc.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\alloca.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\strings.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\memory.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\limits \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cstdint \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\tags.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\settings.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithmfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compatibility.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sched.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\time.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\time.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\equally_split.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find_selectors.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algo.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\algorithmfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_heap.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tempbuf.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_construct.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\new \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\alloc_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\alloc_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\memoryfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\allocator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++allocator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\new_allocator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\random \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cmath \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\math.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\limits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\limits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\limits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\internal_types.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\machine\limits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\syslimits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\page.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\string \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stringfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\char_traits.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\postypes.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cwchar \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\wchar.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\time.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\siginfo.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\siginfo.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\localefwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++locale.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\clocale \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\locale.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\iosfwd \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cctype \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\ctype.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream_insert.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cxxabi_forced.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\range_access.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\atomicity.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr-default.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\pthread.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\signal.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\signal.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\signal.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\sigcontext.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\ucontext.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\user.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\unistd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\select.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\sys\sysconf.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\capability.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\pathconf.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\atomic_word.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\string_conversions.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cerrno \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\errno.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\linux\errno.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm\errno.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\errno.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\asm-generic\errno-base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functional_hash.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\vector \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_uninitialized.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_vector.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_bvector.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\vector.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\vector \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\concurrence.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\vector \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\functional \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tuple \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\array \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\stdexcept \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\array \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\array \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\uses_allocator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hash_func.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_node.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_trace.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\unordered_map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\aligned_buffer.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable_policy.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\unordered_map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\unordered_map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\type_traits \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\functional_hash.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable_policy.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\fstream \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\istream \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ios \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ios_base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\streambuf \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\cwctype \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\wctype.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_base.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf_iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_inline.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ostream \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\istream.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\codecvt.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\basic_file.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++io.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\fstream.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_algos.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_state.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hashtable_size.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_container_size.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\sstream \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\sstream.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_map_to_unordered_map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_size.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_to_list.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_slist.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_vector.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\iterator_tracker.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\opt_random.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\numeric \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_numeric.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numeric \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numericfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\iterator.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\par_loop.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\workstealing.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_number.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cmath \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\gamma.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\special_function_util.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\bessel_function.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\beta_function.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\ell_integral.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\exp_integral.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hypergeometric.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\legendre_function.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\modified_bessel_func.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_hermite.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_laguerre.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\riemann_zeta.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each_selectors.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partial_sum.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithm \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algo.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\sort.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\checkers.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_mergesort.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_merge.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\losertree.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiseq_selection.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\queue \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\deque \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_deque.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\deque.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\deque \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\deque \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_queue.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\quicksort.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partition.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\balanced_quicksort.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\queue.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop_static.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\search.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_shuffle.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\merge.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\unique_copy.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\set_operations.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtypeinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsysinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlogging.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qflags.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qatomic.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbasicatomic.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qatomic_bootstrap.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qgenericatomic.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qatomic_cxx11.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\atomic \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_base.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qatomic_msvc.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qglobalstatic.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmutex.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\chrono \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ratio \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\ctime \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\parse_numbers.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qnumeric.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qversiontagging.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtgui-config.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcoreapplication.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstring.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qchar.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbytearray.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qrefcount.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qnamespace.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qarraydata.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\iterator \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stream_iterator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstringbuilder.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qobjectdefs.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qobjectdefs_impl.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qalgorithms.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qiterator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qhashfunctions.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpair.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\list \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_list.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\list.tcc \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\list \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\list \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbytearraylist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstringlist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qregexp.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstringmatcher.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcoreevent.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qscopedpointer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmetatype.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qvarlengtharray.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcontainerfwd.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tree.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_multimap.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\multimap.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\multimap.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qobject_impl.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qeventloop.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qwindowdefs.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qwindowdefs_win.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qinputmethod.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlocale.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qvariant.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmap.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdebug.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qhash.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtextstream.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qiodevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qvector.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpoint.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qset.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcontiguouscache.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsharedpointer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qshareddata.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsharedpointer_impl.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsize.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\QQmlApplicationEngine \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlapplicationengine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlengine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qurl.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qurlquery.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qjsengine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qjsvalue.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qtqmlglobal.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qtqml-config.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtNetwork\qtnetworkglobal.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtNetwork\qtnetwork-config.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqml.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlprivate.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlparserstatus.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmllist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmetaobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmlerror.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtQml\qqmldebug.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QtGui \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QtGuiDepends \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QtCore \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QtCoreDepends \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstractanimation.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstracteventdispatcher.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstractitemmodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstractnativeeventfilter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstractproxymodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstractstate.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qabstracttransition.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qanimationgroup.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qarraydataops.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qarraydatapointer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbasictimer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbitarray.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbuffer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qbytearraymatcher.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcache.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcollator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcommandlineoption.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcommandlineparser.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qcryptographichash.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdatastream.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdatetime.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdeadlinetimer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qelapsedtimer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdir.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfileinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfile.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfiledevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qdiriterator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qeasingcurve.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qendian.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qeventtransition.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qexception.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfactoryinterface.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfileselector.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QObject \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QStringList \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfilesystemwatcher.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfinalstate.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfuture.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfutureinterface.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qrunnable.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qresultstore.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfuturesynchronizer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qfuturewatcher.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qhistorystate.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qidentityproxymodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qisenum.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qitemselectionmodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qjsonarray.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qjsonvalue.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qjsondocument.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qjsonobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlibrary.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlibraryinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qversionnumber.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qline.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlinkedlist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qlockfile.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qloggingcategory.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmargins.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmath.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmessageauthenticationcode.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmimedata.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmimedatabase.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qmimetype.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qobjectcleanuphandler.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qoperatingsystemversion.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qparallelanimationgroup.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpauseanimation.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qplugin.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpointer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpluginloader.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qprocess.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qpropertyanimation.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qvariantanimation.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qqueue.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qreadwritelock.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qrect.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qregularexpression.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qresource.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsavefile.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qscopedvaluerollback.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsemaphore.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsequentialanimationgroup.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsettings.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsharedmemory.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsignalmapper.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsignaltransition.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsocketnotifier.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsortfilterproxymodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstack.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstandardpaths.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstate.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstatemachine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstorageinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qstringlistmodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qsystemsemaphore.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtemporarydir.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QScopedPointer \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtemporaryfile.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtextboundaryfinder.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtextcodec.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qthread.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qthreadpool.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qthreadstorage.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtimeline.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtimer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtimezone.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtranslator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtypetraits.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\quuid.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qwaitcondition.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qwineventnotifier.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qxmlstream.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qtcoreversion.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qabstracttextdocumentlayout.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextlayout.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qcolor.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qrgb.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qrgba64.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qevent.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qregion.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qkeysequence.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qvector2d.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtouchdevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextformat.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qfont.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpen.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qbrush.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qmatrix.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpolygon.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtransform.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpainterpath.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qimage.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpaintdevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpixelformat.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpixmap.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextoption.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qglyphrun.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qrawfont.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qfontdatabase.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextcursor.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextdocument.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpalette.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qaccessible.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qaccessiblebridge.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qaccessibleobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qaccessibleplugin.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qbackingstore.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qwindow.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QEvent \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QMargins \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QRect \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qsurface.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qsurfaceformat.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qicon.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qcursor.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qbitmap.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qclipboard.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qdesktopservices.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qdrag.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qfontinfo.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qfontmetrics.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qgenericmatrix.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qgenericplugin.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qgenericpluginfactory.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qiconengine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qiconengineplugin.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qimageiohandler.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qimagereader.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qimagewriter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qmatrix4x4.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qvector3d.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qvector4d.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qquaternion.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qmovie.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qoffscreensurface.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengl.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\qt_windows.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\GLES2\gl2.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\GLES2\gl2platform.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\KHR\khrplatform.h \
		..\..\AppData\Local\Android\sdk\ndk-bundle\platforms\android-16\arch-arm\usr\include\inttypes.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengles2ext.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglext.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglbuffer.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglcontext.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QSurfaceFormat \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglversionfunctions.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengldebug.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglextrafunctions.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglfunctions.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglframebufferobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglpaintdevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglpixeltransferoptions.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QSharedDataPointer \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglshaderprogram.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengltexture.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengltextureblitter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QMatrix3x3 \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QMatrix4x4 \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopengltimerquery.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglvertexarrayobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qopenglwindow.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QPaintDeviceWindow \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpaintdevicewindow.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QWindow \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QPaintDevice \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QOpenGLContext \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QImage \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpagedpaintdevice.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpagelayout.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpagesize.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpaintengine.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpainter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpdfwriter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpicture.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpictureformatplugin.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qpixmapcache.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qrasterwindow.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qscreen.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QList \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QSize \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtCore\QSizeF \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\QTransform \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qsessionmanager.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qstandarditemmodel.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qstatictext.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qstylehints.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qsyntaxhighlighter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextobject.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextdocumentfragment.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextdocumentwriter.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtextlist.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtexttable.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qvalidator.h \
		..\..\..\..\Qt\Qt5.9.1\5.9.1\android_armv7\include\QtGui\qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a exit 1
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\armeabi-v7a 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

